name: Api test for dummy website
on:
  push:
    branches:
      - api-testing
  pull_request:
    branches:
      - "api-testing"
      - "!hitfix/*"
      - "!main"
jobs: 
  test: 
   runs-on: ubuntu-latest
   steps: 
    - name: Checkout
      uses: actions/checkout@v3
    - name: Add node
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: npm ci
    # - name: Run api Tests
    #   run: npm run test